[env]
PATH = "$PATH:$scrPath"
XDG_CURRENT_DESKTOP = "Hyprland"
XDG_SESSION_TYPE = "wayland"
XDG_SESSION_DESKTOP = "Hyprland"
QT_QPA_PLATFORM = "wayland"
QT_QPA_PLATFORMTHEME = "qt6ct"
QT_WAYLAND_DISABLE_WINDOWDECORATION = "1"
QT_AUTO_SCREEN_SCALE_FACTOR = "1"
MOZ_ENABLE_WAYLAND = "1"
GDK_SCALE = "1"
XDG_MENU_PREFIX = "arch-"

[startup]
commands = [
  "corectrl",
  "gnome-keyring-daemon",
  "polkit-gnome-authentication-agent-1",
  "$scrPath/resetxdgportal.sh",
  "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
  "dbus-update-activation-environment --systemd --all",
  "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
  "hypridle",
  "waybar",
  "blueman-applet",
  "udiskie --no-automount --smart-tray",
  "nm-applet --indicator",
  "dunst",
  "swww-daemon",
  "$scrPath/swwwallpaper.sh",
  "./scripts/flatpak_themes.sh",
  "sleep 5 && flatpak run com.github.zocker_160.SyncThingy",
  "sway-audio-idle-inhibit",
  "wobber.sh"
]

[shortcuts]
"Super+Return" = "kitty"
"Super+Shift+Return" = "scratchpad.sh"
"Super+W" = "zen-browser"
"Super+R" = "nautilus --new-window"
"Super+Shift+R" = "kitty -e yazi"
"Ctrl+Shift+Escape" = "$scrPath/sysmonlaunch.sh"
"Super+Tab" = "$scrPath/rofilaunch.sh w"
"Super+D" = "$scrPath/rofilaunch.sh d"
"Super+Shift+D" = "$scrPath/rofilaunch.sh r"
"Super+Shift+E" = "$scrPath/rofilaunch.sh f"
"Super+P" = "$scrPath/screenshot.sh s"
"Super+Ctrl+P" = "$scrPath/screenshot.sh sf"
"Super+Alt+P" = "$scrPath/screenshot.sh m"
"Super+Shift+P" = "$scrPath/screenshot.sh p"
"Super+Backspace" = "$scrPath/logoutlaunch.sh"
"Super+Shift+Q" = "hyprlock"
"Super+G" = "/home/tinker/.local/bin/hyper/hyprlocker.sh"
"Super+Alt+Right" = "$scrPath/swwwallpaper.sh -n"
"Super+Alt+Left" = "$scrPath/swwwallpaper.sh -p"
