# vim: filetype=sh
abbr cac "cd /home/tinker/.cache; and ls -A"
abbr cf "cd /home/tinker/.config; and ls -A"
abbr Cff "cd /home/tinker/.config/fish; and ls -A"
abbr cy "cd /home/tinker/.config/yazi; and ls -A"
abbr D "cd /home/tinker/Downloads; and ls -A"
abbr d "cd /home/tinker/Documents; and ls -A"
abbr dt "cd /home/tinker/.local/share; and ls -A"
abbr rr "cd /home/tinker/.config/rofi/; and ls -A"
abbr h "cd /home/tinker/; and ls -A"
abbr m "cd /mnt/; and ls -A"
abbr pp "cd /home/tinker/Pictures; and ls -A"
abbr sc "cd /home/tinker/.local/bin; and ls -A"
abbr ss "cd /home/tinker/.local/bin/statusbar; and ls -A"
abbr sd "cd /home/tinker/.local/bin/dmenu; and ls -A"
abbr sp "cd /home/tinker/.local/bin/personal; and ls -A"
abbr hs "cd /home/tinker/.local/bin/hyde; and ls -A"
abbr src "cd /home/tinker/.local/src; and ls -A"
abbr vn "cd /home/tinker/.config/nvim; and ls -A"
abbr vnc "cd /home/tinker/.config/nvim/lua/core; and ls -A"
abbr vnp "cd /home/tinker/.config/nvim/lua/plugins; and ls -A"
abbr do "cd /home/tinker/WaylandDots/; and ls -A"
abbr hh "cd /home/tinker/.config/hypr/; and ls -A"
abbr wb "cd /home/tinker/.config/waybar/; and ls -A"
abbr bf "nvim /home/tinker/.config/shell/bm-files" 
abbr bd "nvim /home/tinker/.config/shell/bm-dirs" 
abbr cfv "nvim /home/tinker/.config/nvim/init.lua" 
abbr cfz "nvim /home/tinker/.config/zsh/.zshrc" 
abbr cfh "nvim /home/tinker/.config/hypr/hyprland.conf" 
abbr cfk "nvim /home/tinker/.config/kitty/kitty.conf" 
abbr cfn "nvim /home/tinker/.config/fontconfig/fonts.conf" 
abbr cfaz "nvim /home/tinker/.config/shell/aliasrc" 
abbr cfa "nvim /home/tinker/.config/fish/aliasesrc.fish" 
abbr cft "nvim /home/tinker/.config/tmux/tmux.conf" 
abbr cfl "nvim /home/tinker/.config/lf/lfrc" 
abbr cfL "nvim /home/tinker/.config/lf/scope" 
abbr cfw "nvim /home/tinker/.config/waybar/config.ctl" 
abbr cfk "nvim /home/tinker/.config/kitty/kitty.conf" 
abbr cfp "nvim /home/tinker/.zprofile" 
abbr cfe "nvim /home/tinker/.zshenv" 
abbr cff "nvim /home/tinker/.config/fish/config.fish" 
