# vim: filetype=sh
abbr cac "cd $HOME/.cache; and ls -A"
abbr cf "cd $HOME/.config; and ls -A"
abbr Cff "cd $HOME/.config/fish; and ls -A"
abbr cy "cd $HOME/.config/yazi; and ls -A"
abbr D "cd $HOME/Downloads; and ls -A"
abbr d "cd $HOME/Documents; and ls -A"
abbr dt "cd $HOME/.local/share; and ls -A"
abbr rr "cd $HOME/.config/rofi/; and ls -A"
abbr h "cd $HOME/; and ls -A"
abbr m "cd /mnt/; and ls -A"
abbr pp "cd $HOME/Pictures; and ls -A"
abbr sc "cd $HOME/.local/bin; and ls -A"
abbr ss "cd $HOME/.local/bin/statusbar; and ls -A"
abbr sd "cd $HOME/.local/bin/dmenu; and ls -A"
abbr sp "cd $HOME/.local/bin/personal; and ls -A"
abbr hs "cd $HOME/.local/bin/hyde; and ls -A"
abbr src "cd $HOME/.local/src; and ls -A"
abbr vn "cd $HOME/.config/nvim; and ls -A"
abbr vnc "cd $HOME/.config/nvim/lua/core; and ls -A"
abbr vnp "cd $HOME/.config/nvim/lua/plugins; and ls -A"
abbr do "cd $HOME/WaylandDots/; and ls -A"
abbr hh "cd $HOME/.config/hypr/; and ls -A"
abbr wb "cd $HOME/.config/waybar/; and ls -A"
abbr nc "cd $HOME/Nextcloud/; and ls -A"
abbr bf "nvim $HOME/.config/shell/bm-files" 
abbr bd "nvim $HOME/.config/shell/bm-dirs" 
abbr cfv "nvim $HOME/.config/nvim/init.lua" 
abbr cfh "nvim $HOME/.config/hypr/hyprland.conf" 
abbr cfk "nvim $HOME/.config/kitty/kitty.conf" 
abbr cfn "nvim $HOME/.config/fontconfig/fonts.conf" 
abbr cfa "nvim $HOME/.config/fish/aliasesrc.fish" 
abbr cft "nvim $HOME/.config/tmux/tmux.conf" 
abbr cfw "nvim $HOME/.config/waybar/config.ctl" 
abbr cfk "nvim $HOME/.config/kitty/kitty.conf" 
abbr cfg "nvim $HOME/.config/ghostty/config" 
abbr cfp "nvim $HOME/.config/fish/config.fish" 
abbr cff "nvim $HOME/.config/fish/config.fish" 
