format = '''
 $directory$git_branch$git_status$time$lua$cmd_duration
 $character'''
command_timeout = 1500
palette = 'colors'

[palettes.colors]
color1 = '#bccf81'
color2 = '#3e4c0c'
color3 = '#e4e3d7'
color4 = '#1f2019'
color5 = '#d8eb9a'
color6 = '#13140d'
color7 = '#13140d'
color8 = '#c4caa9'
color9 = '#a1d0c5'

# prompt symbols 
# [character]
# success_symbol = "[➜](color9 bold)"
# error_symbol = "[➜](red)"
# vicmd_symbol = "[<](yellow)"

# [directory]
# format = "[](fg:color1 bg:color4)[ ](bg:color1 fg:color2)[ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[](fg:color4) "

# [git_branch]
# format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[](fg:color4) "
# truncation_length = 4
# truncation_symbol = ''

# [git_status]
# format = '([](fg:color4)[ $all_status$ahead_behind ](fg:color3 bg:color4)[](fg:color4)) '
# disabled = false

[time]
# format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[](fg:color4) "
disabled = false
time_format = "%r" # hour:minute format

[cmd_duration]
format = '[$duration](fg:color3)'
min_time = 2000
