"$schema" = 'https://starship.rs/config-schema.json'

#Prompt
format = """
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status\
$cmd_duration\
$jobs\
$character"""
add_newline = false
command_timeout = 1500

[character] 
success_symbol = '[➜]()'
error_symbol = '[➜]()'
vimcmd_symbol = '[V]()'

[package]
disabled = true

[username]
format = '[$user]($style)@'
disabled = false
show_always = true
[directory]
# truncation_length = 2
# truncation_symbol = '…/'
truncate_to_repo = true
home_symbol	= ' ~'


[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false


[git_branch]
format = '[$branch(:$remote_branch)]($style) '
truncation_length = 4
truncation_symbol = ''

[cmd_duration]
format = '[$duration]($style) '
min_time = 2_000

[jobs]
format = '[$symbol$number]($style)'
symbol = '+ '
number_threshold = 4
symbol_threshold = 2

[sudo]
format = '[$symbol]($style)'
symbol = '🧙 '
disabled = true

[status]
symbol = '🔴'
success_symbol = '🟢'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = true
