format = '''
 $directory$git_branch$git_status$time$lua$cmd_duration
 $character'''
command_timeout = 1500


palette = 'colors'

[palettes.colors]
color1 = '#93cdf6'
color2 = '#00344c'
color3 = '#c1c7ce'
color4 = '#1c2024'
color5 = '#00344c'
color6 = '#101417'
color7 = '#101417'
color8 = '#93cdf6'
color9 = '#cdc0e9'

# # Prompt symbols 
# [character]
# success_symbol = "[➜](color9 bold)"
# error_symbol = "[➜](@{error})"
# vicmd_symbol = "[<](#f9e2af)"
#
# [directory]
# format = "[](fg:color1 bg:color4)[ ](bg:color1 fg:color2)[ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[](fg:color4) "
#
# [git_branch]
# format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[](fg:color4) "
# truncation_length = 4
# truncation_symbol = ''
#
# [git_status]
# format = '([](fg:color4)[ $all_status$ahead_behind ](fg:color3 bg:color4)[](fg:color4)) '
# disabled = false
#
#
[time]
# format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format
#
[cmd_duration]
format = '[$duration](fg:color3)'
min_time = 2000
