format = '''
$directory$git_branch$time$cmd_duration
$character'''
command_timeout = 1500




palette = 'colors'

[palettes.colors]
color1 = '#f9b1db'
color2 = '#501e40'
color3 = '#d3c2c9'
color4 = '#251e21'
color5 = '#501e40'
color6 = '#181115'
color7 = '#181115'
color8 = '#f9b1db'
color9 = '#f4ba9e'

# Prompt symbols 
[character]
success_symbol = "[➜](color9 bold)"
error_symbol = "[➜](@{error})"
vicmd_symbol = "[<](#f9e2af)"

[directory]
format = "[](fg:color1 bg:color4)[ ](bg:color1 fg:color2)[ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[](fg:color4)"

[git_branch]
format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[](fg:color4) "
truncation_length = 4
truncation_symbol = ''

[cmd_duration]
format = '[[](fg:color4)$duration](fg:color3 bg:color4)[](fg:color4) '
min_time = 2000

[time]
format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

