#-----------------------------
# Hypridle Configuration
#-----------------------------

# Lock & Suspend commands
LockCMD = "pidof hyprlock || hyprlock"


# Wrap shell logic in scripts if needed
general {
    lock_cmd = $LockCMD
    before_sleep_cmd = loginctl lock-session
    on_unlock_cmd = pidof waybar || setsid -f waybar
    after_sleep_cmd = hyprctl dispatch dpms on
}

#-----------------------------
# Listeners
#-----------------------------
listener {
    timeout = 180 # 3 mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 240 # 4 mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend 
}
