# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 20

# Environment
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment --all
exec-once = ~/.local/bin/omarchy/toggle-waybar

# Theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Tahoe-Dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'MacTahoe-dark'

# XDG Portals
exec-once = systemctl --user start xdg-desktop-portal-hyprland.service
exec-once = systemctl --user start xdg-desktop-portal.service

# Clipboard
exec-once = uwsm app -a cliphist-text -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -a cliphist-image -- wl-paste --type image --watch cliphist store

# Services
exec-once = uwsm app -a swww-daemon -- swww-daemon
exec-once = uwsm app -a swayosd-server -- swayosd-server
exec-once = uwsm app -a sway-audio-idle-inhibit -- sway-audio-idle-inhibit

# Applets
exec-once = uwsm app -a blueman-applet -- blueman-applet
exec-once = uwsm app -a nm-applet -- nm-applet --indicator
exec-once = uwsm app -a udiskie -- udiskie --no-automount --smart-tray

# Authentication
exec-once = uwsm app -a gnome-keyring -- gnome-keyring-daemon --start --components=secrets,ssh
exec-once = uwsm app -a hyprpolkitagent -- /usr/lib/hyprpolkitagent/hyprpolkitagent

# Applications
exec-once = uwsm app -a gsconnect -- gapplication launch org.gnome.Shell.Extensions.GSConnect
exec-once = uwsm app -a nextcloud -- flatpak run com.nextcloud.desktopclient.nextcloud
exec-once = uwsm app -a trash-empty -- trash-empty 30

# Portal Restart
exec-once = systemctl --user restart xdg-desktop-portal
