#-----------------------------
# Hypridle Configuration
#-----------------------------

# Lock & Suspend commands
# Wrap shell logic in scripts if needed
general {
    lock_cmd = /home/tinker/.local/bin/personal/hyprlock_wrapper.sh
    before_sleep_cmd = loginctl lock-session
    on_unlock_cmd = pidof waybar || setsid -f waybar
    # Alternative (restart waybar after unlock)
    # on_unlock_cmd = sleep 1.4 && killall -9 waybar && setsid -f waybar
}

#-----------------------------
# Listeners
#-----------------------------
listener {
    timeout = 180 # 3 mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 240 # 4 mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 540 # 9 mins
    on-timeout = /home/tinker/.local/bin/personal/hypr_suspend_wrapper.sh
}



# $lock_cmd = pidof hyprlock || hyprlock
# $suspend_cmd = pidof steam || systemctl suspend || loginctl suspend # fuck nvidia
#
# general {
#     lock_cmd = $lock_cmd
#     before_sleep_cmd = loginctl lock-session
#     on_unlock_cmd = pidof waybar || setsid -f waybar
#     #on_unlock_cmd = sleep 1.4 && killall -9 waybar && setsid -f waybar
#
# }
#
# listener {
#     timeout = 180 # 3mins
#     on-timeout = loginctl lock-session
# }
#
# listener {
#     timeout = 240 # 4mins
#     on-timeout = hyprctl dispatch dpms off
#     on-resume =  hyprctl dispatch dpms on
#
# listener {
#     timeout = 540 # 9mins
#     on-timeout = $suspend_cmd
# }
