# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in file in `custom`

# Defaults
source = ./hypr.conf
source = ./hyprexec.conf
source = ./hyprkeys.conf
source = ./hyprenv.conf
source = ./rules.conf
source = ./monitors.conf
source = ./permission.conf
#source = ./hyprland/colors.conf
source = ./themes/hyprland-colors.conf
