$THEME_COLOR = e4e3d7
$CURSOR_COLOR = 2d331c

general {
    col.active_border = rgba(bccf81ff) rgba(0d0f08ff) 45deg
    col.inactive_border = rgba(444930ff)
}



decoration {
    rounding = 14
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
