$THEME_COLOR = f0dede
$CURSOR_COLOR = 442929

general {
    col.active_border = rgba(ffb3b3ff) rgba(140c0cff) 45deg
    col.inactive_border = rgba(5d3f3fff)
}



decoration {
    rounding = 14
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
