$THEME_COLOR = eae2d4
$CURSOR_COLOR = 383016

general {
    col.active_border = rgba(e1c46dff) rgba(110e07ff) 45deg
    col.inactive_border = rgba(50462aff)
}



decoration {
    rounding = 14
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
